name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore RestifyNet/RestifyNet.sln

      - name: Build
        run: dotnet build RestifyNet/RestifyNet.sln --configuration Release --no-restore

      - name: Pack
        run: dotnet pack RestifyNet/RestifyNet.sln --configuration Release --no-build -o ./packages

      - name: Publish to NuGet
        if: github.event.action == 'created'
        run: dotnet nuget push ./packages/*.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json

      - name: Publish to GitHub Packages
        if: github.event.action == 'created'
        run: dotnet nuget push ./packages/*.nupkg --skip-duplicate --api-key ${{ secrets.GH_PAT }} --source https://nuget.pkg.github.com/PedroCavaleiro/index.json
